spring.application.name=smartinventory

# ── Base de datos PostgreSQL ────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/smartinventory
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# update — actualiza el esquema sin borrar datos existentes
spring.jpa.hibernate.ddl-auto=update

# Muestra el SQL generado por Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
